## broker/emqx.conf

node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"
  data_dir = "data"
}

mqtt {
  max_packet_size = 1MB
  max_clientid_len = 128
  session_expiry_interval = 7200s   # 2 hours session persistence
  retain_available = true
  wildcard_subscription = true
  shared_subscription = true
  max_topic_alias = 64              # per connection
  response_information = "farm-response"
  max_inflight = 32                 # moved from listener
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024
}

listeners.ws.default {
  bind = "0.0.0.0:8083"
  websocket.mqtt_path = "/mqtt"
}

dashboard {
  listeners.http {
    bind = 18083
  }
}
